#!/bin/bash
set -x

DIR="$1"
USER="$2"
PCKGA="$3"
PCKGB="$4"
PCKGC="$5"

# To be run under sudo su...

cd /var/www/$DIR
composer require $PCKGA/$PCKGB
#chown -R $USER:www-data storage bootstrap/cache resources/views database app/Models
php artisan optimize:clear
composer dump-autoload
echo "0" | php artisan vendor:publish --force

mkdir /home/$USER/staging/$PCKGA
mkdir /home/$USER/staging/$PCKGA/$PCKGB
cp -R /var/www/$DIR/vendor/$PCKGA/$PCKGB/src /home/$USER/staging/$PCKGA/$PCKGB/src
cp -R /var/www/$DIR/vendor/rockhopsoft/survloop/src /home/$USER/staging/rockhopsoft/survloop/src
cp -R /var/www/$DIR/vendor/rockhopsoft/survloop-libraries/src /home/$USER/staging/rockhopsoft/survloop-libraries/src

chown -R $USER:$USER /home/$USER/survloop
chown -R $USER:$USER /home/$USER/staging

echo "yes" | php artisan migrate
# php artisan db:seed --class=SurvLoopSeeder
# php artisan db:seed --class=ZipCodeSeeder
# php artisan db:seed --class=$PCKGC

echo "Y" | apt install aide
aideinit
cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf

reboot
