#!/bin/bash
set -x

DIR="$1"
PCKG="$2"

# To be run under sudo su...

php artisan cache:clear
composer require rockhopsoft/survloop
composer require $PCKG

#sed -i 's///g' /var/www/$DIR/composer.json










echo "Y" | apt install aide
aideinit
cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db
cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf
